### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by azii7** [Norikiru/bloxflip-autocrash#23] opened 2022-11-04 21:20 UTC
Hey i've had this issue with the crash bot where it would say my username user ID balance and etc but after a few moments it would display this error: [ELEMENTS]      Unable to query element: div.gameBlock.gameBet.crash_crashBet__D5Rs_ > button

May I please get a fix or a reason as to why this is happening, thanks.

**Comment by carince** [comment] 2022-11-05 17:24
Duplicate of #22

**Closed as completed by carince** 2022-11-05 17:25 UTC
